# Generated by Django 2.0 on 2018-06-27 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swaps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swaps',
            old_name='image',
            new_name='imagefun',
        ),
    ]
