# Generated by Django 2.0 on 2018-06-27 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swaps', '0002_auto_20180627_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swaps',
            old_name='imagefun',
            new_name='image',
        ),
    ]
