# Generated by Django 2.0 on 2018-06-27 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swaps', '0003_auto_20180627_0101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Swaps',
            new_name='Swap',
        ),
    ]
