# Generated by Django 2.0 on 2018-06-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaps', '0004_auto_20180627_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swap',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
